### ISSUE TITLE
`import_mappings` requires `HEROKU_AUTH_TOKEN` to be set

### ISSUE THREAD

**Issue by amureki** [Thermondo/django-heroku-connect#68]
Hi,

the documentation says that `HEROKU_AUTH_TOKEN` is optional and required only for `healthcheck`:
https://django-heroku-connect.readthedocs.io/en/latest/settings.html#heroku_connect.conf.HerokuConnectAppConf.HEROKU_AUTH_TOKEN

I did set an application without a `healthcheck` plugin, but while running `import_mappings` command, I am gettings the next error:
`AttributeError: 'Settings' object has no attribute 'HEROKU_AUTH_TOKEN'`

Full traceback:
```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/app/src/django-heroku-connect/heroku_connect/management/commands/import_mappings.py", line 37, in handle
    connections = self.get_connections(app_name)
  File "/app/src/django-heroku-connect/heroku_connect/management/commands/import_mappings.py", line 105, in get_connections
    return utils.get_connections(app_name)
  File "/app/src/django-heroku-connect/heroku_connect/utils.py", line 199, in get_connections
    response = requests.get(url, params=payload, headers=_get_authorization_headers())
  File "/app/src/django-heroku-connect/heroku_connect/utils.py", line 162, in _get_authorization_headers
    'Authorization': 'Bearer %s' % settings.HEROKU_AUTH_TOKEN
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'HEROKU_AUTH_TOKEN'
```

**Comment by codingjoe** [comment]
This is not a package issue but related to a bug in django-configurations (and the reason why I don't want to use it ;), see https://github.com/jazzband/django-configurations/issues/167
